USE sakila;
#Write SQL queries to perform the following tasks using the Sakila database:

#List the number of films per category.

SELECT
    c.category_id,
    c.name AS category_name,
    COUNT(f.film_id) AS number_of_films
FROM
    category c
JOIN
    film_category fc ON c.category_id = fc.category_id
JOIN
    film f ON fc.film_id = f.film_id
GROUP BY
    c.category_id, c.name
ORDER BY
    number_of_films DESC;

#Retrieve the store ID, city, and country for each store. Take into considerati


SELECT
    s.store_id,
    ci.city,
    co.country
FROM
    store s
JOIN
    address a ON s.address_id = a.address_id
JOIN
    city ci ON a.city_id = ci.city_id
JOIN
    country co ON ci.country_id = co.country_id;

#Calculate the total revenue generated by each store in dollars.


SELECT
    s.store_id,
    SUM(p.amount) AS total_revenue
FROM
    store s
JOIN
    staff sf ON s.manager_staff_id = sf.staff_id
JOIN
    payment p ON sf.staff_id = p.staff_id
GROUP BY
    s.store_id;

#Determine the average running time of films for each category.


SELECT
    fc.category_id,
    AVG(f.length) AS average_running_time
FROM
    film_category fc
JOIN
    film f ON fc.film_id = f.film_id
GROUP BY
    fc.category_id;

